In [1]:
#Super store data

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\vigne\Desktop\superstore data project\train.csv")

In [4]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62

In [5]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

In [6]:
df.columns=df.columns.str.replace(" ","_")

In [7]:
df.columns=df.columns.str.replace("-","_")

In [8]:
df.columns=df.columns.str.lower()

In [9]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales'],
      dtype='object')

In [10]:
df.isnull().sum()

row_id            0
order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_id       0
customer_name     0
segment           0
country           0
city              0
state             0
postal_code      11
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
dtype: int64

In [11]:
cols_with_null = df.columns[df.isnull().any()]
print(cols_with_null)

Index(['postal_code'], dtype='object')

In [12]:
df[df['postal_code'].isnull()][['city', 'state', 'postal_code']]

            city    state  postal_code
2234  Burlington  Vermont          NaN
5274  Burlington  Vermont          NaN
8798  Burlington  Vermont          NaN
9146  Burlington  Vermont          NaN
9147  Burlington  Vermont          NaN
9148  Burlington  Vermont          NaN
9386  Burlington  Vermont          NaN
9387  Burlington  Vermont          NaN
9388  Burlington  Vermont          NaN
9389  Burlington  Vermont          NaN
9741  Burlington  Vermont          NaN

In [27]:
df[df['city'] == 'Burlington'][['city', 'state', 'postal_code']]

            city           state  postal_code
683   Burlington  North Carolina      27217.0
684   Burlington  North Carolina      27217.0
1008  Burlington            Iowa      52601.0
1038  Burlington  North Carolina      27217.0
1039  Burlington  North Carolina      27217.0
1393  Burlington  North Carolina      27217.0
2234  Burlington         Vermont       5401.0
2928  Burlington  North Carolina      27217.0
5065  Burlington  North Carolina      27217.0
5066  Burlington  North Carolina      27217.0
5274  Burlington         Vermont       5401.0
8317  Burlington  North Carolina      27217.0
8318  Burlington  North Carolina      27217.0
8410  Burlington  North Carolina      27217.0
8798  Burlington         Vermont       5401.0
9146  Burlington         Vermont       5401.0
9147  Burlington         Vermont       5401.0
9148  Burlington         Vermont       5401.0
9209  Burlington            Iowa      52601.0
9210  Burlington            Iowa      52601.0
9386  Burlington         Vermont       5401.0
9387  Burlington         Vermont       5401.0
9388  Burlington         Vermont       5401.0
9389  Burlington         Vermont       5401.0
9741  Burlington         Vermont       5401.0

In [23]:
df[df['city'] == 'Burlington']['postal_code'].mode()

0    27217.0
Name: postal_code, dtype: float64

In [13]:
df.loc[
    (df['city'] == 'Burlington') & (df['state'] == 'Vermont'),
    'postal_code'
] = 05401.0

In [14]:
#Since Burlington has multiple ZIP codes but the dataset operates at city level, I used the most frequent or standard ZIP code 
#to maintain consistency and avoid introducing noise.”

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9800 non-null   int64
 1   order_id       9800 non-null   object
 2   order_date     9800 non-null   object
 3   ship_date      9800 non-null   object
 4   ship_mode      9800 non-null   object
 5   customer_id    9800 non-null   object
 6   customer_name  9800 non-null   object
 7   segment        9800 non-null   object
 8   country        9800 non-null   object
 9   city           9800 non-null   object
 10  state          9800 non-null   object
 11  postal_code    9800 non-null   float64
 12  region         9800 non-null   object
 13  product_id     9800 non-null   object
 14  category       9800 non-null   object
 15  sub_category   9800 non-null   object
 16  product_name   9800 non-null   object
 17  sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [16]:
df.describe()

            row_id   postal_code         sales
count  9800.000000   9800.000000   9800.000000
mean   4900.500000  55217.343265    230.769059
std    2829.160653  32066.750532    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  57551.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
#I converted string dates into datetime format using pandas, handled inconsistent formats using dayfirst=True, 
# and safely managed invalid values using errors='coerce'

In [19]:
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True, errors='coerce')
df['ship_date'] = pd.to_datetime(df['ship_date'], dayfirst=True, errors='coerce')

In [20]:
df[['order_date','order_date']].isnull().sum()

order_date    0
order_date    0
dtype: int64

In [33]:
df['sales']= df['sales'].round(2)

In [34]:
df['sales'].sum()

np.float64(2261536.55)

In [35]:
df.to_csv(r'C:\Users\vigne\Desktop\superstore data project\clean_superstore.csv', index=False)

In [39]:
from sqlalchemy import create_engine
engine = create_engine(
    "postgresql+psycopg2://postgres:Vinosql%405@localhost:5432/Super_store_db"
)

In [40]:
df.to_sql(
    name='super_store_data',
    con=engine,
    if_exists='replace',   # 'replace', 'append', 'fail'
    index=False
)

800

In [41]:
#“I use Pandas with SQLAlchemy for standard loads and PostgreSQL COPY for high-performance bulk inserts.”

In [42]:
import os
os.getcwd()

'C:\\Users\\vigne'